
from nintendo import account

api = account.AccountAPI()
pid = api.get_pid("Kinnay-WiiU")
mii = api.get_mii(pid)
print("NNID:", mii.nnid)
print("PID:", pid) #Same as mii.pid
print("Name:", mii.name)

info = mii.data
print("Mii:")
print("\tBirthday: %i-%i" %(info.birth_day, info.birth_month))
print("\tCreator name:", info.creator_name)
print("\tMii color:", info.color)
print("\tMii size: %i%%" %(info.size / 128 * 100))
print("\tMii weight: %i%%" %(info.fatness / 128 * 100))
print("\tGender:", ["Male", "Female"][info.gender])
print("\t----------")
print("\tBlush style:", info.blush_type)
print("\tFace style:", info.face_style)
print("\tFace color:", info.face_color)
print("\tFace shape:", info.face_type)
print("\t----------")
print("\tHair style:", info.hair_type)
print("\tHair color:", info.hair_color)
print("\tHair mirrored:", ["No", "Yes"][info.hair_mirrored])
print("\t----------")
print("\tEye style:", info.eye_type)
print("\tEye color:", info.eye_color)
print("\tEye size:", info.eye_scale)
print("\tEye thickness:", info.eye_thickness)
print("\tEye height:", info.eye_height)
print("\tEye distance:", info.eye_distance)
print("\tEye rotation:", info.eye_rotation)
print("\t----------")
print("\tEyebrow style:", info.eyebrow_type)
print("\tEyebrow color:", info.eyebrow_color)
print("\tEyebrow size:", info.eyebrow_scale)
print("\tEyebrow thickness:", info.eyebrow_thickness)
print("\tEyebrow height:", info.eyebrow_height)
print("\tEyebrow distance:", info.eyebrow_distance)
print("\tEyebrow rotation:", info.eyebrow_rotation)
print("\t----------")
print("\tNose style:", info.nose_type)
print("\tNose size:", info.nose_scale)
print("\tNose height:", info.nose_height)
print("\t----------")
print("\tMouth style:", info.mouth_type)
print("\tMouth color:", info.mouth_color)
print("\tMouth size:", info.mouth_scale)
print("\tMouth thickness:", info.mouth_thickness)
print("\tMouth height:", info.mouth_height)
print("\t----------")
print("\tMustache style:", info.mustache_type)
if info.mustache_type:
	print("\tMustache height:", info.mustache_height)
	print("\tMustache size:", info.mustache_scale)
print("\tBeard style:", info.beard_type)
if info.beard_type:
	print("\tBeard color:", info.beard_color)
print("\t----------")
print("\tGlasses style:", info.glass_type)
if info.glass_type:
	print("\tGlasses color:", info.glass_color)
	print("\tGlasses size:", info.glass_scale)
	print("\tGlasses height:", info.glass_height)
print("\t----------")
print("\tMole:", ["No", "Yes"][info.mole_enabled])
if info.mole_enabled:
	print("\tMole size:", info.mole_scale)
	print("\tMole X:", info.mole_xpos)
	print("\tMole Y:", info.mole_ypos)

print("Images:")
for url in mii.images.values():
	print("\t%s" %url)
