name: Ruff

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Check code quality with Ruff
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    
    - name: Run Ruff linter
      run: ruff check --output-format=github .
    
    - name: Run Ruff formatter check
      run: ruff format --check .